// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcwFkZ7mPUejH9bWsuRZCd61eFYlGmWis',
    appId: '1:1015349474898:web:7da58afe203dc65580518b',
    messagingSenderId: '1015349474898',
    projectId: 'ai-life-assistant-d2731',
    authDomain: 'ai-life-assistant-d2731.firebaseapp.com',
    storageBucket: 'ai-life-assistant-d2731.firebasestorage.app',
    measurementId: 'G-T15ZYCLD3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5kJxv3NiZEyehFPFLlnLQjDR4RTA54ZA',
    appId: '1:1015349474898:android:b5b8d74356f91ebb80518b',
    messagingSenderId: '1015349474898',
    projectId: 'ai-life-assistant-d2731',
    storageBucket: 'ai-life-assistant-d2731.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDhJbOjGc3t_ljFrhU0eW_ZaUe1XZa_L0',
    appId: '1:1015349474898:ios:91b810571122910b80518b',
    messagingSenderId: '1015349474898',
    projectId: 'ai-life-assistant-d2731',
    storageBucket: 'ai-life-assistant-d2731.firebasestorage.app',
    iosBundleId: 'com.example.aiLifeAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDhJbOjGc3t_ljFrhU0eW_ZaUe1XZa_L0',
    appId: '1:1015349474898:ios:91b810571122910b80518b',
    messagingSenderId: '1015349474898',
    projectId: 'ai-life-assistant-d2731',
    storageBucket: 'ai-life-assistant-d2731.firebasestorage.app',
    iosBundleId: 'com.example.aiLifeAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcwFkZ7mPUejH9bWsuRZCd61eFYlGmWis',
    appId: '1:1015349474898:web:7fb661fb8bf9c52b80518b',
    messagingSenderId: '1015349474898',
    projectId: 'ai-life-assistant-d2731',
    authDomain: 'ai-life-assistant-d2731.firebaseapp.com',
    storageBucket: 'ai-life-assistant-d2731.firebasestorage.app',
    measurementId: 'G-JKE4PVN5BE',
  );
}
